---
title: "Preparation of TPM tables for RF in T cell susbsets"
author: "Benoit Nicolet"
date: "27/01/2021"
output: html_document
---

```{r setup, include=FALSE}

library(plyr)
library(dplyr)
library(doMC)
library(randomForest)
library(biomaRt)
library(ggplot2)
library(tidyverse)
library(caret)
library(e1071)


knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set("/home/ben/Analysis/RF_human/")
setwd("/home/ben/Analysis/RF_human/")


```


```{r BiomaRt}
## Biomart ##
ensembl <- useEnsembl(biomart="ensembl",dataset="hsapiens_gene_ensembl", host = "http://apr2018.archive.ensembl.org")

tx2gene <- getBM(attributes=c("ensembl_transcript_id_version","external_gene_name","gene_biotype"), mart = ensembl)
tx2gene <- subset(tx2gene,tx2gene$gene_biotype=="protein_coding")


```


```{r Jurkat stab 0 to 1h}
Jurkat_Rest_1 <- read.delim("/home/ben/Analysis/RF_human/Jurkat_stability/Salmon_output/total_Un_1_SRR2130272/quant.sf")
Jurkat_Rest_2 <- read.delim("/home/ben/Analysis/RF_human/Jurkat_stability/Salmon_output/total_Un_2_SRR2130273/quant.sf")
Jurkat_Rest_3 <- read.delim("/home/ben/Analysis/RF_human/Jurkat_stability/Salmon_output/total_Un_3_SRR2130274/quant.sf")

Jurkat_1h_1 <- read.delim("/home/ben/Analysis/RF_human/Jurkat_stability/Salmon_output/total_1h_1_SRR2130275/quant.sf")
Jurkat_1h_2 <- read.delim("/home/ben/Analysis/RF_human/Jurkat_stability/Salmon_output/total_1h_2_SRR2130276/quant.sf")

Jurkat_1h_4SU_1 <- read.delim("/home/ben/Analysis/RF_human/Jurkat_stability/Salmon_output/4SU_1h_1_SRR2130289//quant.sf")
Jurkat_1h_4SU_2 <- read.delim("/home/ben/Analysis/RF_human/Jurkat_stability/Salmon_output/4SU_1h_2_SRR2130290//quant.sf")





Jurkat_Rest_1 <- data.frame("ID"=Jurkat_Rest_1$Name,"Jurkat_Rest_1_TPM"=Jurkat_Rest_1$TPM)
Jurkat_Rest_2 <- data.frame("ID"=Jurkat_Rest_2$Name,"Jurkat_Rest_2_TPM"=Jurkat_Rest_2$TPM)
Jurkat_Rest_3 <- data.frame("ID"=Jurkat_Rest_3$Name,"Jurkat_Rest_3_TPM"=Jurkat_Rest_3$TPM)

Jurkat_1h_1 <- data.frame("ID"=Jurkat_1h_1$Name,"Jurkat_1h_1_TPM"=Jurkat_1h_1$TPM)
Jurkat_1h_2 <- data.frame("ID"=Jurkat_1h_2$Name,"Jurkat_1h_2_TPM"=Jurkat_1h_2$TPM)

Jurkat_1h_4SU_1 <- data.frame("ID"=Jurkat_1h_4SU_1$Name,"Jurkat_1h_4SU_1_TPM"=Jurkat_1h_4SU_1$TPM)
Jurkat_1h_4SU_2 <- data.frame("ID"=Jurkat_1h_4SU_2$Name,"Jurkat_1h_4SU_2_TPM"=Jurkat_1h_4SU_2$TPM)


Jurkat <- list(Jurkat_Rest_1,Jurkat_Rest_2,Jurkat_Rest_3,Jurkat_1h_1,Jurkat_1h_2,Jurkat_1h_4SU_1,Jurkat_1h_4SU_2)

Jurkat <- join_all(Jurkat,by = "ID")

Jurkat <- subset(Jurkat, 
                 (Jurkat$Jurkat_Rest_1_TPM>0 &
                 Jurkat$Jurkat_Rest_2_TPM>0 &
                 Jurkat$Jurkat_Rest_3_TPM>0) |
                 (Jurkat$Jurkat_1h_1_TPM>0 &
                 Jurkat$Jurkat_1h_2_TPM>0 )|
                 (Jurkat$Jurkat_1h_4SU_1_TPM>0 &
                 Jurkat$Jurkat_1h_4SU_2_TPM>0 ))

Jurkat$Jurkat_Rest <- (Jurkat$Jurkat_Rest_1_TPM + Jurkat$Jurkat_Rest_2_TPM + Jurkat$Jurkat_Rest_3_TPM)/3
Jurkat$Jurkat_1h <- (Jurkat$Jurkat_1h_1_TPM + Jurkat$Jurkat_1h_1_TPM)/2
Jurkat$Jurkat_1h_4SU <- (Jurkat$Jurkat_1h_4SU_1_TPM + Jurkat$Jurkat_1h_4SU_2_TPM)/2


Jurkat$Stab_0_1 <- (Jurkat$Jurkat_1h - Jurkat$Jurkat_1h_4SU) / Jurkat$Jurkat_Rest

Jurkat <- subset(Jurkat, 
                 (Jurkat$Jurkat_Rest_1_TPM>10 &
                 Jurkat$Jurkat_Rest_2_TPM>10 &
                 Jurkat$Jurkat_Rest_3_TPM>10) &
                 (Jurkat$Jurkat_1h_1_TPM>10 &
                 Jurkat$Jurkat_1h_2_TPM>10 )&
                 (Jurkat$Jurkat_1h_4SU_1_TPM>10 &
                 Jurkat$Jurkat_1h_4SU_2_TPM>10 ))

hist(Jurkat$Stab_0_1)


```





