---
title: "Preparation of TPM tables for RF in T cell susbsets"
author: "Benoit Nicolet"
date: "27/01/2021"
output: html_document
---

```{r setup, include=FALSE}

library(plyr)
library(dplyr)
library(doMC)
library(randomForest)
library(biomaRt)
library(ggplot2)
library(tidyverse)
library(caret)
library(e1071)


knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set("/home/ben/Analysis/RF_human/")
setwd("/home/ben/Analysis/RF_human/")


```


```{r BiomaRt}
## Biomart ##
ensembl <- useEnsembl(biomart="ensembl",dataset="hsapiens_gene_ensembl", host = "http://apr2018.archive.ensembl.org")

tx2gene <- getBM(attributes=c("ensembl_transcript_id_version","ensembl_transcript_id","external_gene_name","gene_biotype"), mart = ensembl)
tx2gene <- subset(tx2gene,tx2gene$gene_biotype=="protein_coding")

```


```{r CD4 Tn}
CD4_Tn1 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tn_1_ERR431571/quant.sf")
CD4_Tn2 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tn_2_ERR431574/quant.sf")
CD4_Tn3 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tn_3_ERR431580/quant.sf")
CD4_Tn4<- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tn_4_ERR431581/quant.sf")
CD4_Tn5 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tn_5_ERR431610/quant.sf")

CD4_Tn1 <- data.frame("ID"=CD4_Tn1$Name,"Tn1_TPM"=CD4_Tn1$TPM)
CD4_Tn2 <- data.frame("ID"=CD4_Tn2$Name,"Tn2_TPM"=CD4_Tn2$TPM)
CD4_Tn3 <- data.frame("ID"=CD4_Tn3$Name,"Tn3_TPM"=CD4_Tn3$TPM)
CD4_Tn4 <- data.frame("ID"=CD4_Tn4$Name,"Tn4_TPM"=CD4_Tn4$TPM)
CD4_Tn5 <- data.frame("ID"=CD4_Tn5$Name,"Tn5_TPM"=CD4_Tn5$TPM)

CD4_Tn <- list(CD4_Tn1,CD4_Tn2,CD4_Tn3,CD4_Tn4,CD4_Tn5)

CD4_Tn <- join_all(CD4_Tn,by = "ID")

CD4_Tn$TPM <- rowMeans(CD4_Tn[2:6])
CD4_Tn <- subset(CD4_Tn,CD4_Tn$TPM>0)
dim(CD4_Tn) # 110680      7

CD4_Tn <- data.frame("ID"=CD4_Tn$ID,"TPM"=CD4_Tn$TPM)

CD4_Tn <- merge(CD4_Tn,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(CD4_Tn) # 102396      4

## making TPM per gene ##
#registerDoMC(4)
#CD4_Tn <- ddply(CD4_Tn,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
CD4_Tn$TPM <- log10(CD4_Tn$TPM)
CD4_Tn <- subset(CD4_Tn, CD4_Tn$TPM>=-1)
log10(1)
colnames(CD4_Tn)[1]="ID"
dim(CD4_Tn) # 85667 tx

CD4_Tn <- data.frame("ID"=CD4_Tn$ensembl_transcript_id, "TPM"=CD4_Tn$TPM)

write.table(CD4_Tn,"/home/ben/Analysis/RF_human/T_cell_subsets/RNA/CD4_Tn_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)


```


```{r CD4 Tcm}
CD4_Tcm1 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tcm_1_ERR431582/quant.sf")
CD4_Tcm2 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tcm_2_ERR431598/quant.sf")
CD4_Tcm3 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tcm_3_ERR431614/quant.sf")
CD4_Tcm4 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tcm_4_ERR431620/quant.sf")
CD4_Tcm5 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tcm_5_ERR431626/quant.sf")

CD4_Tcm1 <- data.frame("ID"=CD4_Tcm1$Name,"Tcm1_TPM"=CD4_Tcm1$TPM)
CD4_Tcm2 <- data.frame("ID"=CD4_Tcm2$Name,"Tcm2_TPM"=CD4_Tcm2$TPM)
CD4_Tcm3 <- data.frame("ID"=CD4_Tcm3$Name,"Tcm3_TPM"=CD4_Tcm3$TPM)
CD4_Tcm4 <- data.frame("ID"=CD4_Tcm4$Name,"Tcm4_TPM"=CD4_Tcm4$TPM)
CD4_Tcm5 <- data.frame("ID"=CD4_Tcm5$Name,"Tcm5_TPM"=CD4_Tcm5$TPM)

CD4_Tcm <- list(CD4_Tcm1,CD4_Tcm2,CD4_Tcm3,CD4_Tcm4,CD4_Tcm5)

CD4_Tcm <- join_all(CD4_Tcm,by = "ID")

CD4_Tcm$TPM <- rowMeans(CD4_Tcm[2:6])
CD4_Tcm <- subset(CD4_Tcm,CD4_Tcm$TPM>0)
dim(CD4_Tcm) # 108621      7

CD4_Tcm <- data.frame("ID"=CD4_Tcm$ID,"TPM"=CD4_Tcm$TPM)

CD4_Tcm <- merge(CD4_Tcm,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(CD4_Tcm) # 99658      4

## making TPM per gene ##
#registerDoMC(4)
#CD4_Tcm <- ddply(CD4_Tcm,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
CD4_Tcm$TPM <- log10(CD4_Tcm$TPM)
CD4_Tcm <- subset(CD4_Tcm, CD4_Tcm$TPM>=-1)
colnames(CD4_Tcm)[1]="ID"
dim(CD4_Tcm) # 82910 tx

CD4_Tcm <- data.frame("ID"=CD4_Tcm$ensembl_transcript_id, "TPM"=CD4_Tcm$TPM)

write.table(CD4_Tcm,"/home/ben/Analysis/RF_human/T_cell_subsets/RNA/CD4_Tcm_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)


```



```{r CD4 Tem}
CD4_Tem1 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tem_1_ERR431575/quant.sf")
CD4_Tem2 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tem_2_ERR431588/quant.sf")
CD4_Tem3 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tem_3_ERR431603/quant.sf")
CD4_Tem4 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD4_Tem_4_ERR431616/quant.sf")


CD4_Tem1 <- data.frame("ID"=CD4_Tem1$Name,"Tem1_TPM"=CD4_Tem1$TPM)
CD4_Tem2 <- data.frame("ID"=CD4_Tem2$Name,"Tem2_TPM"=CD4_Tem2$TPM)
CD4_Tem3 <- data.frame("ID"=CD4_Tem3$Name,"Tem3_TPM"=CD4_Tem3$TPM)
CD4_Tem4 <- data.frame("ID"=CD4_Tem4$Name,"Tem4_TPM"=CD4_Tem4$TPM)


CD4_Tem <- list(CD4_Tem1,CD4_Tem2,CD4_Tem3,CD4_Tem4)

CD4_Tem <- join_all(CD4_Tem,by = "ID")

CD4_Tem$TPM <- rowMeans(CD4_Tem[2:5])
CD4_Tem <- subset(CD4_Tem,CD4_Tem$TPM>0)
dim(CD4_Tem) # 107605      7

CD4_Tem <- data.frame("ID"=CD4_Tem$ID,"TPM"=CD4_Tem$TPM)

CD4_Tem <- merge(CD4_Tem,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(CD4_Tem) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#CD4_Tem <- ddply(CD4_Tem,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
CD4_Tem$TPM <- log10(CD4_Tem$TPM)
CD4_Tem <- subset(CD4_Tem, CD4_Tem$TPM>=-1)
colnames(CD4_Tem)[1]="ID"
dim(CD4_Tem) # 86058 tx 

CD4_Tem <- data.frame("ID"=CD4_Tem$ensembl_transcript_id, "TPM"=CD4_Tem$TPM)

write.table(CD4_Tem,"/home/ben/Analysis/RF_human/T_cell_subsets/RNA/CD4_Tem_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)


```



```{r CD8 Tn}
CD8_Tn1 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tn_1_SRR6298258/quant.sf")
CD8_Tn2 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tn_2_SRR6298286/quant.sf")
CD8_Tn3 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tn_3_SRR6298315/quant.sf")
CD8_Tn4 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tn_4_SRR6298344/quant.sf")


CD8_Tn1 <- data.frame("ID"=CD8_Tn1$Name,"Tn1_TPM"=CD8_Tn1$TPM)
CD8_Tn2 <- data.frame("ID"=CD8_Tn2$Name,"Tn2_TPM"=CD8_Tn2$TPM)
CD8_Tn3 <- data.frame("ID"=CD8_Tn3$Name,"Tn3_TPM"=CD8_Tn3$TPM)
CD8_Tn4 <- data.frame("ID"=CD8_Tn4$Name,"Tn4_TPM"=CD8_Tn4$TPM)


CD8_Tn <- list(CD8_Tn1,CD8_Tn2,CD8_Tn3,CD8_Tn4)

CD8_Tn <- join_all(CD8_Tn,by = "ID")

CD8_Tn$TPM <- rowMeans(CD8_Tn[2:5])
CD8_Tn <- subset(CD8_Tn,CD8_Tn$TPM>0)
dim(CD8_Tn) # 93455      6

CD8_Tn <- data.frame("ID"=CD8_Tn$ID,"TPM"=CD8_Tn$TPM)

CD8_Tn <- merge(CD8_Tn,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(CD8_Tn) # 86705      4

## making TPM per gene ##
#registerDoMC(4)
#CD8_Tn <- ddply(CD8_Tn,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
CD8_Tn$TPM <- log10(CD8_Tn$TPM)
CD8_Tn <- subset(CD8_Tn, CD8_Tn$TPM>=-1)
colnames(CD8_Tn)[1]="ID"
dim(CD8_Tn) # 82493 tx

CD8_Tn <- data.frame("ID"=CD8_Tn$ensembl_transcript_id, "TPM"=CD8_Tn$TPM)

write.table(CD8_Tn,"/home/ben/Analysis/RF_human/T_cell_subsets/RNA/CD8_Tn_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```



```{r CD8 Tcm}
CD8_Tcm1 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tcm_1_SRR6298259/quant.sf")
CD8_Tcm2 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tcm_2_SRR6298287/quant.sf")
CD8_Tcm3 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tcm_3_SRR6298316/quant.sf")
CD8_Tcm4 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tcm_4_SRR6298345/quant.sf")


CD8_Tcm1 <- data.frame("ID"=CD8_Tcm1$Name,"Tcm1_TPM"=CD8_Tcm1$TPM)
CD8_Tcm2 <- data.frame("ID"=CD8_Tcm2$Name,"Tcm2_TPM"=CD8_Tcm2$TPM)
CD8_Tcm3 <- data.frame("ID"=CD8_Tcm3$Name,"Tcm3_TPM"=CD8_Tcm3$TPM)
CD8_Tcm4 <- data.frame("ID"=CD8_Tcm4$Name,"Tcm4_TPM"=CD8_Tcm4$TPM)


CD8_Tcm <- list(CD8_Tcm1,CD8_Tcm2,CD8_Tcm3,CD8_Tcm4)

CD8_Tcm <- join_all(CD8_Tcm,by = "ID")

CD8_Tcm$TPM <- rowMeans(CD8_Tcm[2:5])
CD8_Tcm <- subset(CD8_Tcm,CD8_Tcm$TPM>0)
dim(CD8_Tcm) # 93455      6

CD8_Tcm <- data.frame("ID"=CD8_Tcm$ID,"TPM"=CD8_Tcm$TPM)

CD8_Tcm <- merge(CD8_Tcm,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(CD8_Tcm) # 86705      4

## making TPM per gene ##
# registerDoMC(4)
# CD8_Tcm <- ddply(CD8_Tcm,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
CD8_Tcm$TPM <- log10(CD8_Tcm$TPM)
CD8_Tcm <- subset(CD8_Tcm, CD8_Tcm$TPM>=-1)
colnames(CD8_Tcm)[1]="ID"
dim(CD8_Tcm) # 83808 tx

CD8_Tcm <- data.frame("ID"=CD8_Tcm$ensembl_transcript_id, "TPM"=CD8_Tcm$TPM)

write.table(CD8_Tcm,"/home/ben/Analysis/RF_human/T_cell_subsets/RNA/CD8_Tcm_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```



```{r CD8 Tem}
CD8_Tem1 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tem_1_SRR6298260/quant.sf")
CD8_Tem2 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tem_2_SRR6298288/quant.sf")
CD8_Tem3 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tem_3_SRR6298317/quant.sf")
CD8_Tem4 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Tem_4_SRR6298346/quant.sf")


CD8_Tem1 <- data.frame("ID"=CD8_Tem1$Name,"Tem1_TPM"=CD8_Tem1$TPM)
CD8_Tem2 <- data.frame("ID"=CD8_Tem2$Name,"Tem2_TPM"=CD8_Tem2$TPM)
CD8_Tem3 <- data.frame("ID"=CD8_Tem3$Name,"Tem3_TPM"=CD8_Tem3$TPM)
CD8_Tem4 <- data.frame("ID"=CD8_Tem4$Name,"Tem4_TPM"=CD8_Tem4$TPM)


CD8_Tem <- list(CD8_Tem1,CD8_Tem2,CD8_Tem3,CD8_Tem4)

CD8_Tem <- join_all(CD8_Tem,by = "ID")

CD8_Tem$TPM <- rowMeans(CD8_Tem[2:5])
CD8_Tem <- subset(CD8_Tem,CD8_Tem$TPM>0)
dim(CD8_Tem) # 93678      6

CD8_Tem <- data.frame("ID"=CD8_Tem$ID,"TPM"=CD8_Tem$TPM)

CD8_Tem <- merge(CD8_Tem,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(CD8_Tem) # 87444      4

## making TPM per gene ##
# registerDoMC(4)
# CD8_Tem <- ddply(CD8_Tem,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
CD8_Tem$TPM <- log10(CD8_Tem$TPM)
CD8_Tem <- subset(CD8_Tem, CD8_Tem$TPM>=-1)
colnames(CD8_Tem)[1]="ID"
dim(CD8_Tem) # 82762 tx

CD8_Tem <- data.frame("ID"=CD8_Tem$ensembl_transcript_id, "TPM"=CD8_Tem$TPM)

write.table(CD8_Tem,"/home/ben/Analysis/RF_human/T_cell_subsets/RNA/CD8_Tem_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```




```{r CD8 Teff}
CD8_Teff1 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Teff_1_SRR6298261/quant.sf")
CD8_Teff2 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Teff_2_SRR6298289/quant.sf")
CD8_Teff3 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Teff_3_SRR6298318/quant.sf")
CD8_Teff4 <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/RNA/Salmon_output/CD8_Teff_4_SRR6298353/quant.sf")


CD8_Teff1 <- data.frame("ID"=CD8_Teff1$Name,"Teff1_TPM"=CD8_Teff1$TPM)
CD8_Teff2 <- data.frame("ID"=CD8_Teff2$Name,"Teff2_TPM"=CD8_Teff2$TPM)
CD8_Teff3 <- data.frame("ID"=CD8_Teff3$Name,"Teff3_TPM"=CD8_Teff3$TPM)
CD8_Teff4 <- data.frame("ID"=CD8_Teff4$Name,"Teff4_TPM"=CD8_Teff4$TPM)


CD8_Teff <- list(CD8_Teff1,CD8_Teff2,CD8_Teff3,CD8_Teff4)

CD8_Teff <- join_all(CD8_Teff,by = "ID")

CD8_Teff$TPM <- rowMeans(CD8_Teff[2:5])
CD8_Teff <- subset(CD8_Teff,CD8_Teff$TPM>0)
dim(CD8_Teff) # 93749      6

CD8_Teff <- data.frame("ID"=CD8_Teff$ID,"TPM"=CD8_Teff$TPM)

CD8_Teff <- merge(CD8_Teff,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(CD8_Teff) # 87309      4

## making TPM per gene ##
# registerDoMC(4)
# CD8_Teff <- ddply(CD8_Teff,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
CD8_Teff$TPM <- log10(CD8_Teff$TPM)
CD8_Teff <- subset(CD8_Teff, CD8_Teff$TPM>=-1)
colnames(CD8_Teff)[1]="ID"
dim(CD8_Teff) # 82292 tx

CD8_Teff <- data.frame("ID"=CD8_Teff$ensembl_transcript_id, "TPM"=CD8_Teff$TPM)

write.table(CD8_Teff,"/home/ben/Analysis/RF_human/T_cell_subsets/RNA/CD8_Teff_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```





### Rest of immune system ###


## Basophils ##
```{r Basophils}
Basophils_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Basophils_A_SRR6298285/quant.sf")
Basophils_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Basophils_B_SRR6298314/quant.sf")
Basophils_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Basophils_C_SRR6298343/quant.sf")
Basophils_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Basophils_D_SRR6298377/quant.sf")


Basophils_A <- data.frame("ID"=Basophils_A$Name,"Basophils_A_TPM"=Basophils_A$TPM)
Basophils_B <- data.frame("ID"=Basophils_B$Name,"Basophils_B_TPM"=Basophils_B$TPM)
Basophils_C <- data.frame("ID"=Basophils_C$Name,"Basophils_C_TPM"=Basophils_C$TPM)
Basophils_D <- data.frame("ID"=Basophils_D$Name,"Basophils_D_TPM"=Basophils_D$TPM)


Basophils <- list(Basophils_A,Basophils_B,Basophils_C,Basophils_D)

Basophils <- join_all(Basophils,by = "ID")

Basophils$TPM <- rowMeans(Basophils[2:5])
Basophils <- subset(Basophils,Basophils$TPM>0)
dim(Basophils) # 107605      7

Basophils <- data.frame("ID"=Basophils$ID,"TPM"=Basophils$TPM)

Basophils <- merge(Basophils,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(Basophils) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#Basophils <- ddply(Basophils,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
Basophils$TPM <- log10(Basophils$TPM)
Basophils <- subset(Basophils, Basophils$TPM>=-1)
colnames(Basophils)[1]="ID"
dim(Basophils) # 79608 tx 

Basophils <- data.frame("ID"=Basophils$ensembl_transcript_id, "TPM"=Basophils$TPM)

write.table(Basophils,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/Basophils_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(Basophils$TPM)


```






## B Naive ##
```{r B_naive}
B_naive_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-naive_A_SRR6298273/quant.sf")
B_naive_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-naive_B_SRR6298302/quant.sf")
B_naive_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-naive_C_SRR6298331/quant.sf")
B_naive_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-naive_D_SRR6298365/quant.sf")


B_naive_A <- data.frame("ID"=B_naive_A$Name,"B_naive_A_TPM"=B_naive_A$TPM)
B_naive_B <- data.frame("ID"=B_naive_B$Name,"B_naive_B_TPM"=B_naive_B$TPM)
B_naive_C <- data.frame("ID"=B_naive_C$Name,"B_naive_C_TPM"=B_naive_C$TPM)
B_naive_D <- data.frame("ID"=B_naive_D$Name,"B_naive_D_TPM"=B_naive_D$TPM)


B_naive <- list(B_naive_A,B_naive_B,B_naive_C,B_naive_D)

B_naive <- join_all(B_naive,by = "ID")

B_naive$TPM <- rowMeans(B_naive[2:5])
B_naive <- subset(B_naive,B_naive$TPM>0)
dim(B_naive) # 107605      7

B_naive <- data.frame("ID"=B_naive$ID,"TPM"=B_naive$TPM)

B_naive <- merge(B_naive,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(B_naive) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#B_naive <- ddply(B_naive,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
B_naive$TPM <- log10(B_naive$TPM)
B_naive <- subset(B_naive, B_naive$TPM>=-1)
colnames(B_naive)[1]="ID"
dim(B_naive) # 84860 tx 

B_naive <- data.frame("ID"=B_naive$ensembl_transcript_id, "TPM"=B_naive$TPM)

write.table(B_naive,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/B_naive_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(B_naive$TPM)

```





## B_NS_mem ##
```{r B_NS_mem}
B_NS_mem_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-NS-mem_A_SRR6298274/quant.sf")
B_NS_mem_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-NS-mem_B_SRR6298303/quant.sf")
B_NS_mem_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-NS-mem_C_SRR6298332/quant.sf")
B_NS_mem_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-NS-mem_D_SRR6298366/quant.sf")


B_NS_mem_A <- data.frame("ID"=B_NS_mem_A$Name,"B_NS_mem_A_TPM"=B_NS_mem_A$TPM)
B_NS_mem_B <- data.frame("ID"=B_NS_mem_B$Name,"B_NS_mem_B_TPM"=B_NS_mem_B$TPM)
B_NS_mem_C <- data.frame("ID"=B_NS_mem_C$Name,"B_NS_mem_C_TPM"=B_NS_mem_C$TPM)
B_NS_mem_D <- data.frame("ID"=B_NS_mem_D$Name,"B_NS_mem_D_TPM"=B_NS_mem_D$TPM)


B_NS_mem <- list(B_NS_mem_A,B_NS_mem_B,B_NS_mem_C,B_NS_mem_D)

B_NS_mem <- join_all(B_NS_mem,by = "ID")

B_NS_mem$TPM <- rowMeans(B_NS_mem[2:5])
B_NS_mem <- subset(B_NS_mem,B_NS_mem$TPM>0)
dim(B_NS_mem) # 107605      7

B_NS_mem <- data.frame("ID"=B_NS_mem$ID,"TPM"=B_NS_mem$TPM)

B_NS_mem <- merge(B_NS_mem,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(B_NS_mem) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#B_NS_mem <- ddply(B_NS_mem,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
B_NS_mem$TPM <- log10(B_NS_mem$TPM)
B_NS_mem <- subset(B_NS_mem, B_NS_mem$TPM>=-1)
colnames(B_NS_mem)[1]="ID"
dim(B_NS_mem) # 83870 tx 

B_NS_mem <- data.frame("ID"=B_NS_mem$ensembl_transcript_id, "TPM"=B_NS_mem$TPM)

write.table(B_NS_mem,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/B_NS_mem_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(B_NS_mem$TPM)

```







## B_plasma ##
```{r B_plasma}
B_plasma_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-plasma_A_SRR6298277/quant.sf")
B_plasma_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-plasma_B_SRR6298306/quant.sf")
B_plasma_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-plasma_C_SRR6298335/quant.sf")
B_plasma_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-plasma_D_SRR6298369/quant.sf")


B_plasma_A <- data.frame("ID"=B_plasma_A$Name,"B_plasma_A_TPM"=B_plasma_A$TPM)
B_plasma_B <- data.frame("ID"=B_plasma_B$Name,"B_plasma_B_TPM"=B_plasma_B$TPM)
B_plasma_C <- data.frame("ID"=B_plasma_C$Name,"B_plasma_C_TPM"=B_plasma_C$TPM)
B_plasma_D <- data.frame("ID"=B_plasma_D$Name,"B_plasma_D_TPM"=B_plasma_D$TPM)


B_plasma <- list(B_plasma_A,B_plasma_B,B_plasma_C,B_plasma_D)

B_plasma <- join_all(B_plasma,by = "ID")

B_plasma$TPM <- rowMeans(B_plasma[2:5])
B_plasma <- subset(B_plasma,B_plasma$TPM>0)
dim(B_plasma) # 107605      7

B_plasma <- data.frame("ID"=B_plasma$ID,"TPM"=B_plasma$TPM)

B_plasma <- merge(B_plasma,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(B_plasma) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#B_plasma <- ddply(B_plasma,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
B_plasma$TPM <- log10(B_plasma$TPM)
B_plasma <- subset(B_plasma, B_plasma$TPM>=-1)
colnames(B_plasma)[1]="ID"
dim(B_plasma) # 69691 tx 

B_plasma <- data.frame("ID"=B_plasma$ensembl_transcript_id, "TPM"=B_plasma$TPM)

write.table(B_plasma,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/B_plasma_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(B_plasma$TPM)

```




## B_S_mem ##
```{r B_S_mem}
B_S_mem_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-S-mem_A_SRR6298276/quant.sf")
B_S_mem_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-S-mem_B_SRR6298305/quant.sf")
B_S_mem_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-S-mem_C_SRR6298334/quant.sf")
B_S_mem_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/B-S-mem_D_SRR6298368/quant.sf")


B_S_mem_A <- data.frame("ID"=B_S_mem_A$Name,"B_S_mem_A_TPM"=B_S_mem_A$TPM)
B_S_mem_B <- data.frame("ID"=B_S_mem_B$Name,"B_S_mem_B_TPM"=B_S_mem_B$TPM)
B_S_mem_C <- data.frame("ID"=B_S_mem_C$Name,"B_S_mem_C_TPM"=B_S_mem_C$TPM)
B_S_mem_D <- data.frame("ID"=B_S_mem_D$Name,"B_S_mem_D_TPM"=B_S_mem_D$TPM)


B_S_mem <- list(B_S_mem_A,B_S_mem_B,B_S_mem_C,B_S_mem_D)

B_S_mem <- join_all(B_S_mem,by = "ID")

B_S_mem$TPM <- rowMeans(B_S_mem[2:5])
B_S_mem <- subset(B_S_mem,B_S_mem$TPM>0)
dim(B_S_mem) # 107605      7

B_S_mem <- data.frame("ID"=B_S_mem$ID,"TPM"=B_S_mem$TPM)

B_S_mem <- merge(B_S_mem,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(B_S_mem) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#B_S_mem <- ddply(B_S_mem,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
B_S_mem$TPM <- log10(B_S_mem$TPM)
B_S_mem <- subset(B_S_mem, B_S_mem$TPM>=-1)
colnames(B_S_mem)[1]="ID"
dim(B_S_mem) # 84583 tx 

B_S_mem <- data.frame("ID"=B_S_mem$ensembl_transcript_id, "TPM"=B_S_mem$TPM)

write.table(B_S_mem,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/B_S_mem_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(B_S_mem$TPM)

```





## mDC ##
```{r mDC}
mDC_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/mDC_A_SRR6298283/quant.sf")
mDC_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/mDC_B_SRR6298312/quant.sf")
mDC_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/mDC_C_SRR6298341/quant.sf")
mDC_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/mDC_D_SRR6298375/quant.sf")


mDC_A <- data.frame("ID"=mDC_A$Name,"mDC_A_TPM"=mDC_A$TPM)
mDC_B <- data.frame("ID"=mDC_B$Name,"mDC_B_TPM"=mDC_B$TPM)
mDC_C <- data.frame("ID"=mDC_C$Name,"mDC_C_TPM"=mDC_C$TPM)
mDC_D <- data.frame("ID"=mDC_D$Name,"mDC_D_TPM"=mDC_D$TPM)


mDC <- list(mDC_A,mDC_B,mDC_C,mDC_D)

mDC <- join_all(mDC,by = "ID")

mDC$TPM <- rowMeans(mDC[2:5])
mDC <- subset(mDC,mDC$TPM>0)
dim(mDC) # 107605      7

mDC <- data.frame("ID"=mDC$ID,"TPM"=mDC$TPM)

mDC <- merge(mDC,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(mDC) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#mDC <- ddply(mDC,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
mDC$TPM <- log10(mDC$TPM)
mDC <- subset(mDC, mDC$TPM>=-1)
colnames(mDC)[1]="ID"
dim(mDC) # 81906 tx 

mDC <- data.frame("ID"=mDC$ensembl_transcript_id, "TPM"=mDC$TPM)

write.table(mDC,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/mDC_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(mDC$TPM)

```






## Mono_classical ##
```{r Mono_classical}
Mono_classical_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-classical_A_SRR6298278/quant.sf")
Mono_classical_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-classical_B_SRR6298307/quant.sf")
Mono_classical_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-classical_C_SRR6298336/quant.sf")
Mono_classical_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-classical_D_SRR6298370/quant.sf")


Mono_classical_A <- data.frame("ID"=Mono_classical_A$Name,"Mono_classical_A_TPM"=Mono_classical_A$TPM)
Mono_classical_B <- data.frame("ID"=Mono_classical_B$Name,"Mono_classical_B_TPM"=Mono_classical_B$TPM)
Mono_classical_C <- data.frame("ID"=Mono_classical_C$Name,"Mono_classical_C_TPM"=Mono_classical_C$TPM)
Mono_classical_D <- data.frame("ID"=Mono_classical_D$Name,"Mono_classical_D_TPM"=Mono_classical_D$TPM)


Mono_classical <- list(Mono_classical_A,Mono_classical_B,Mono_classical_C,Mono_classical_D)

Mono_classical <- join_all(Mono_classical,by = "ID")

Mono_classical$TPM <- rowMeans(Mono_classical[2:5])
Mono_classical <- subset(Mono_classical,Mono_classical$TPM>0)
dim(Mono_classical) # 107605      7

Mono_classical <- data.frame("ID"=Mono_classical$ID,"TPM"=Mono_classical$TPM)

Mono_classical <- merge(Mono_classical,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(Mono_classical) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#Mono_classical <- ddply(Mono_classical,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
Mono_classical$TPM <- log10(Mono_classical$TPM)
Mono_classical <- subset(Mono_classical, Mono_classical$TPM>=-1)
colnames(Mono_classical)[1]="ID"
dim(Mono_classical) # 80196 tx 

Mono_classical <- data.frame("ID"=Mono_classical$ensembl_transcript_id, "TPM"=Mono_classical$TPM)

write.table(Mono_classical,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/Mono_classical_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(Mono_classical$TPM)

```





## Mono_inter ##
```{r Mono_inter}
Mono_inter_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-inter_A_SRR6298279/quant.sf")
Mono_inter_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-inter_B_SRR6298308/quant.sf")
Mono_inter_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-inter_C_SRR6298337/quant.sf")
Mono_inter_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-inter_D_SRR6298371/quant.sf")


Mono_inter_A <- data.frame("ID"=Mono_inter_A$Name,"Mono_inter_A_TPM"=Mono_inter_A$TPM)
Mono_inter_B <- data.frame("ID"=Mono_inter_B$Name,"Mono_inter_B_TPM"=Mono_inter_B$TPM)
Mono_inter_C <- data.frame("ID"=Mono_inter_C$Name,"Mono_inter_C_TPM"=Mono_inter_C$TPM)
Mono_inter_D <- data.frame("ID"=Mono_inter_D$Name,"Mono_inter_D_TPM"=Mono_inter_D$TPM)


Mono_inter <- list(Mono_inter_A,Mono_inter_B,Mono_inter_C,Mono_inter_D)

Mono_inter <- join_all(Mono_inter,by = "ID")

Mono_inter$TPM <- rowMeans(Mono_inter[2:5])
Mono_inter <- subset(Mono_inter,Mono_inter$TPM>0)
dim(Mono_inter) # 107605      7

Mono_inter <- data.frame("ID"=Mono_inter$ID,"TPM"=Mono_inter$TPM)

Mono_inter <- merge(Mono_inter,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(Mono_inter) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#Mono_inter <- ddply(Mono_inter,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
Mono_inter$TPM <- log10(Mono_inter$TPM)
Mono_inter <- subset(Mono_inter, Mono_inter$TPM>=-1)
colnames(Mono_inter)[1]="ID"
dim(Mono_inter) # 80551 tx 

Mono_inter <- data.frame("ID"=Mono_inter$ensembl_transcript_id, "TPM"=Mono_inter$TPM)

write.table(Mono_inter,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/Mono_inter_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(Mono_inter$TPM)


```









## Mono_non_classical ##
```{r Mono_non_classical}
Mono_non_classical_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-non-classical_A_SRR6298280/quant.sf")
Mono_non_classical_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-non-classical_B_SRR6298309/quant.sf")
Mono_non_classical_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-non-classical_C_SRR6298338/quant.sf")
Mono_non_classical_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Mono-non-classical_D_SRR6298372/quant.sf")


Mono_non_classical_A <- data.frame("ID"=Mono_non_classical_A$Name,"Mono_non_classical_A_TPM"=Mono_non_classical_A$TPM)
Mono_non_classical_B <- data.frame("ID"=Mono_non_classical_B$Name,"Mono_non_classical_B_TPM"=Mono_non_classical_B$TPM)
Mono_non_classical_C <- data.frame("ID"=Mono_non_classical_C$Name,"Mono_non_classical_C_TPM"=Mono_non_classical_C$TPM)
Mono_non_classical_D <- data.frame("ID"=Mono_non_classical_D$Name,"Mono_non_classical_D_TPM"=Mono_non_classical_D$TPM)


Mono_non_classical <- list(Mono_non_classical_A,Mono_non_classical_B,Mono_non_classical_C,Mono_non_classical_D)

Mono_non_classical <- join_all(Mono_non_classical,by = "ID")

Mono_non_classical$TPM <- rowMeans(Mono_non_classical[2:5])
Mono_non_classical <- subset(Mono_non_classical,Mono_non_classical$TPM>0)
dim(Mono_non_classical) # 107605      7

Mono_non_classical <- data.frame("ID"=Mono_non_classical$ID,"TPM"=Mono_non_classical$TPM)

Mono_non_classical <- merge(Mono_non_classical,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(Mono_non_classical) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#Mono_non_classical <- ddply(Mono_non_classical,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
Mono_non_classical$TPM <- log10(Mono_non_classical$TPM)
Mono_non_classical <- subset(Mono_non_classical, Mono_non_classical$TPM>=-1)
colnames(Mono_non_classical)[1]="ID"
dim(Mono_non_classical) # 81644 tx 

Mono_non_classical <- data.frame("ID"=Mono_non_classical$ensembl_transcript_id, "TPM"=Mono_non_classical$TPM)

write.table(Mono_non_classical,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/Mono_non_classical_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(Mono_non_classical$TPM)


```






## Neutrophils ##
```{r Neutrophils}
Neutrophils_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Neutrophils_A_SRR6298284/quant.sf")
Neutrophils_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Neutrophils_B_SRR6298313/quant.sf")
Neutrophils_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Neutrophils_C_SRR6298342/quant.sf")
Neutrophils_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Neutrophils_D_SRR6298376/quant.sf")


Neutrophils_A <- data.frame("ID"=Neutrophils_A$Name,"Neutrophils_A_TPM"=Neutrophils_A$TPM)
Neutrophils_B <- data.frame("ID"=Neutrophils_B$Name,"Neutrophils_B_TPM"=Neutrophils_B$TPM)
Neutrophils_C <- data.frame("ID"=Neutrophils_C$Name,"Neutrophils_C_TPM"=Neutrophils_C$TPM)
Neutrophils_D <- data.frame("ID"=Neutrophils_D$Name,"Neutrophils_D_TPM"=Neutrophils_D$TPM)


Neutrophils <- list(Neutrophils_A,Neutrophils_B,Neutrophils_C,Neutrophils_D)

Neutrophils <- join_all(Neutrophils,by = "ID")

Neutrophils$TPM <- rowMeans(Neutrophils[2:5])
Neutrophils <- subset(Neutrophils,Neutrophils$TPM>0)
dim(Neutrophils) # 107605      7

Neutrophils <- data.frame("ID"=Neutrophils$ID,"TPM"=Neutrophils$TPM)

Neutrophils <- merge(Neutrophils,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(Neutrophils) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#Neutrophils <- ddply(Neutrophils,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
Neutrophils$TPM <- log10(Neutrophils$TPM)
Neutrophils <- subset(Neutrophils, Neutrophils$TPM>=-1)
colnames(Neutrophils)[1]="ID"
dim(Neutrophils) # 65863 tx 

Neutrophils <- data.frame("ID"=Neutrophils$ensembl_transcript_id, "TPM"=Neutrophils$TPM)

write.table(Neutrophils,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/Neutrophils_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(Neutrophils$TPM)


```







## NK ##
```{r NK}
NK_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/NK_A_SRR6298281/quant.sf")
NK_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/NK_B_SRR6298310/quant.sf")
NK_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/NK_C_SRR6298339/quant.sf")
NK_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/NK_D_SRR6298373/quant.sf")


NK_A <- data.frame("ID"=NK_A$Name,"NK_A_TPM"=NK_A$TPM)
NK_B <- data.frame("ID"=NK_B$Name,"NK_B_TPM"=NK_B$TPM)
NK_C <- data.frame("ID"=NK_C$Name,"NK_C_TPM"=NK_C$TPM)
NK_D <- data.frame("ID"=NK_D$Name,"NK_D_TPM"=NK_D$TPM)


NK <- list(NK_A,NK_B,NK_C,NK_D)

NK <- join_all(NK,by = "ID")

NK$TPM <- rowMeans(NK[2:5])
NK <- subset(NK,NK$TPM>0)
dim(NK) # 107605      7

NK <- data.frame("ID"=NK$ID,"TPM"=NK$TPM)

NK <- merge(NK,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(NK) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#NK <- ddply(NK,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
NK$TPM <- log10(NK$TPM)
NK <- subset(NK, NK$TPM>=-1)
colnames(NK)[1]="ID"
dim(NK) # 85765 tx 

NK <- data.frame("ID"=NK$ensembl_transcript_id, "TPM"=NK$TPM)

write.table(NK,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/NK_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(NK$TPM)


```






## pDC ##
```{r pDC}
pDC_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/pDC_A_SRR6298282/quant.sf")
pDC_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/pDC_B_SRR6298311/quant.sf")
pDC_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/pDC_C_SRR6298340/quant.sf")
pDC_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/pDC_D_SRR6298374/quant.sf")


pDC_A <- data.frame("ID"=pDC_A$Name,"pDC_A_TPM"=pDC_A$TPM)
pDC_B <- data.frame("ID"=pDC_B$Name,"pDC_B_TPM"=pDC_B$TPM)
pDC_C <- data.frame("ID"=pDC_C$Name,"pDC_C_TPM"=pDC_C$TPM)
pDC_D <- data.frame("ID"=pDC_D$Name,"pDC_D_TPM"=pDC_D$TPM)


pDC <- list(pDC_A,pDC_B,pDC_C,pDC_D)

pDC <- join_all(pDC,by = "ID")

pDC$TPM <- rowMeans(pDC[2:5])
pDC <- subset(pDC,pDC$TPM>0)
dim(pDC) # 107605      7

pDC <- data.frame("ID"=pDC$ID,"TPM"=pDC$TPM)

pDC <- merge(pDC,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(pDC) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#pDC <- ddply(pDC,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
pDC$TPM <- log10(pDC$TPM)
pDC <- subset(pDC, pDC$TPM>=-1)
colnames(pDC)[1]="ID"
dim(pDC) # 82086 tx 

pDC <- data.frame("ID"=pDC$ensembl_transcript_id, "TPM"=pDC$TPM)

write.table(pDC,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/pDC_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(pDC$TPM)


```





## Tregs ##
```{r Tregs}
Tregs_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Treg_A_SRR6298266/quant.sf")
Tregs_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Treg_B_SRR6298294/quant.sf")
Tregs_C <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Treg_C_SRR6298323/quant.sf")
Tregs_D <- read.delim("/home/ben/Analysis/RF_human/immune_system/RNA/Salmon_output/Treg_D_SRR6298358/quant.sf")


Tregs_A <- data.frame("ID"=Tregs_A$Name,"Tregs_A_TPM"=Tregs_A$TPM)
Tregs_B <- data.frame("ID"=Tregs_B$Name,"Tregs_B_TPM"=Tregs_B$TPM)
Tregs_C <- data.frame("ID"=Tregs_C$Name,"Tregs_C_TPM"=Tregs_C$TPM)
Tregs_D <- data.frame("ID"=Tregs_D$Name,"Tregs_D_TPM"=Tregs_D$TPM)


Tregs <- list(Tregs_A,Tregs_B,Tregs_C,Tregs_D)

Tregs <- join_all(Tregs,by = "ID")

Tregs$TPM <- rowMeans(Tregs[2:5])
Tregs <- subset(Tregs,Tregs$TPM>0)
dim(Tregs) # 107605      7

Tregs <- data.frame("ID"=Tregs$ID,"TPM"=Tregs$TPM)

Tregs <- merge(Tregs,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(Tregs) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#Tregs <- ddply(Tregs,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
Tregs$TPM <- log10(Tregs$TPM)
Tregs <- subset(Tregs, Tregs$TPM>=-1)
colnames(Tregs)[1]="ID"
dim(Tregs) # 84662 tx 

Tregs <- data.frame("ID"=Tregs$ensembl_transcript_id, "TPM"=Tregs$TPM)

write.table(Tregs,"/home/ben/Analysis/RF_human/immune_system/RNA/preped_RNA_data/Tregs_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(Tregs$TPM)


```













### Cell lines ###



## HEK293T ##
```{r HEK293T}
HEK293T_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/cell_lines_ref/Salmon_output/trimmed_HEK293T_A_SRR8449591.sra/quant.sf")
HEK293T_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/cell_lines_ref/Salmon_output/trimmed_HEK293T_B_SRR8449592.sra/quant.sf")


HEK293T_A <- data.frame("ID"=HEK293T_A$Name,"HEK293T_A_TPM"=HEK293T_A$TPM)
HEK293T_B <- data.frame("ID"=HEK293T_B$Name,"HEK293T_B_TPM"=HEK293T_B$TPM)


HEK293T <- list(HEK293T_A,HEK293T_B)

HEK293T <- join_all(HEK293T,by = "ID")

HEK293T$TPM <- rowMeans(HEK293T[2:3])
HEK293T <- subset(HEK293T,HEK293T$TPM>0)
dim(HEK293T) # 107605      7

HEK293T <- data.frame("ID"=HEK293T$ID,"TPM"=HEK293T$TPM)

HEK293T <- merge(HEK293T,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(HEK293T) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#HEK293T <- ddply(HEK293T,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
HEK293T$TPM <- log10(HEK293T$TPM)
HEK293T <- subset(HEK293T, HEK293T$TPM>=-1)
colnames(HEK293T)[1]="ID"
dim(HEK293T) # 84662 tx 

HEK293T <- data.frame("ID"=HEK293T$ensembl_transcript_id, "TPM"=HEK293T$TPM)

write.table(HEK293T,"/home/ben/Analysis/RF_human/immune_system/cell_lines_ref/HEK293T_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(HEK293T$TPM)


```






## HeLa ##
```{r HeLa}
HeLa_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/cell_lines_ref/Salmon_output/HeLa_A_SRR8449597.sra/quant.sf")
HeLa_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/cell_lines_ref/Salmon_output/HeLa_B_SRR8449599.sra/quant.sf")


HeLa_A <- data.frame("ID"=HeLa_A$Name,"HeLa_A_TPM"=HeLa_A$TPM)
HeLa_B <- data.frame("ID"=HeLa_B$Name,"HeLa_B_TPM"=HeLa_B$TPM)


HeLa <- list(HeLa_A,HeLa_B)

HeLa <- join_all(HeLa,by = "ID")

HeLa$TPM <- rowMeans(HeLa[2:3])
HeLa <- subset(HeLa,HeLa$TPM>0)
dim(HeLa) # 107605      7

HeLa <- data.frame("ID"=HeLa$ID,"TPM"=HeLa$TPM)

HeLa <- merge(HeLa,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(HeLa) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#HeLa <- ddply(HeLa,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
HeLa$TPM <- log10(HeLa$TPM)
HeLa <- subset(HeLa, HeLa$TPM>=-1)
colnames(HeLa)[1]="ID"
dim(HeLa) # 84662 tx 

HeLa <- data.frame("ID"=HeLa$ensembl_transcript_id, "TPM"=HeLa$TPM)

write.table(HeLa,"/home/ben/Analysis/RF_human/immune_system/cell_lines_ref/HeLa_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(HeLa$TPM)


```







## K562 ##
```{r K562}
K562_A <- read.delim("/home/ben/Analysis/RF_human/immune_system/cell_lines_ref/Salmon_output/K562_A_SRR8449604.sra/quant.sf")
K562_B <- read.delim("/home/ben/Analysis/RF_human/immune_system/cell_lines_ref/Salmon_output/K562_B_SRR8449603.sra/quant.sf")


K562_A <- data.frame("ID"=K562_A$Name,"K562_A_TPM"=K562_A$TPM)
K562_B <- data.frame("ID"=K562_B$Name,"K562_B_TPM"=K562_B$TPM)


K562 <- list(K562_A,K562_B)

K562 <- join_all(K562,by = "ID")

K562$TPM <- rowMeans(K562[2:3])
K562 <- subset(K562,K562$TPM>0)
dim(K562) # 107605      7

K562 <- data.frame("ID"=K562$ID,"TPM"=K562$TPM)

K562 <- merge(K562,tx2gene,by.x="ID", by.y="ensembl_transcript_id_version",all.x=F) ## Here I put all.x=F to loose the TPM of non-coding transcripts (TCR, IGs, pseudogenes...)
dim(K562) # 98773      4

## making TPM per gene ##
#registerDoMC(4)
#K562 <- ddply(K562,"external_gene_name", numcolwise(sum), .parallel = T, .progress = T)
K562$TPM <- log10(K562$TPM)
K562 <- subset(K562, K562$TPM>=-1)
colnames(K562)[1]="ID"
dim(K562) # 84662 tx 

K562 <- data.frame("ID"=K562$ensembl_transcript_id, "TPM"=K562$TPM)

write.table(K562,"/home/ben/Analysis/RF_human/immune_system/cell_lines_ref/K562_TPM_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

hist(K562$TPM)


```





