---
title: "Preparation of CN tables for RF in T cell susbsets"
author: "Benoit Nicolet"
date: "27/01/2021"
output: html_document
---

```{r setup, include=FALSE}

library(plyr)
library(dplyr)
library(doMC)
library(randomForest)
library(biomaRt)
library(ggplot2)
library(tidyverse)
library(caret)
library(e1071)


knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set("/home/ben/Analysis/RF_human/")
setwd("/home/ben/Analysis/RF_human/")


```



```{r Protein library v1}

Sequence_parameters <- read.delim("/home/ben/Analysis/RF_human/Library_V2_Aug2021/Protein_per_Uniprot_entry_library_v2_RBP_GC_length_codon_AA_m6A_m5C_AtoI_m1A_m7G_CD8miRDB_PTM.csv", sep="\t", dec=".")
#Sequence_parameters$ID <- rownames(Sequence_parameters)

CN_MANN <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CN_fromLFQ_mann.txt")
CN_MANN <- data.frame(CN_MANN[,533:537],CN_MANN %>% dplyr::select(contains("copy")))
CN_MANN <- data.frame(CN_MANN[,1:4],CN_MANN %>% dplyr::select(contains("steady")))
CN_MANN$T..Protein.names <- NULL
CN_MANN$T..Gene.name <- NULL #mapply(strsplit(as.character(CN_MANN$T..Gene.names),";"),FUN=function(x){(as.character(x)[1])})

dim(CN_MANN)

# Making a unique protein ID column # 

CN_MANN$Entry_1 <- mapply(strsplit(as.character(CN_MANN$T..Majority.protein.IDs),";"),FUN=function(x){(as.character(x)[1])})
CN_MANN$Entry_2 <- mapply(strsplit(as.character(CN_MANN$T..Majority.protein.IDs),";"),FUN=function(x){(as.character(x)[2])})
CN_MANN$Entry_3 <- mapply(strsplit(as.character(CN_MANN$T..Majority.protein.IDs),";"),FUN=function(x){(as.character(x)[3])})
CN_MANN$Entry_4 <- mapply(strsplit(as.character(CN_MANN$T..Majority.protein.IDs),";"),FUN=function(x){(as.character(x)[4])})
CN_MANN$Entry_5 <- mapply(strsplit(as.character(CN_MANN$T..Majority.protein.IDs),";"),FUN=function(x){(as.character(x)[5])})
CN_MANN$Entry_6 <- mapply(strsplit(as.character(CN_MANN$T..Majority.protein.IDs),";"),FUN=function(x){(as.character(x)[6])})

dim(CN_MANN)
dim(CN_MANN[CN_MANN$Entry_1 %in% Sequence_parameters$Entry,])
dim(CN_MANN[CN_MANN$Entry_6 %in% Sequence_parameters$Entry,])


CN_MANN$Entry[CN_MANN$Entry_1 %in% Sequence_parameters$Entry] <- CN_MANN$Entry_1[CN_MANN$Entry_1 %in% Sequence_parameters$Entry]
dim(CN_MANN[CN_MANN$Entry %in% Sequence_parameters$Entry,])


CN_MANN$Entry <- ifelse((CN_MANN$Entry_2 %in% Sequence_parameters$Entry)==TRUE & is.na(CN_MANN$Entry)==TRUE, CN_MANN$Entry_2,CN_MANN$Entry)

dim(CN_MANN[CN_MANN$Entry %in% Sequence_parameters$Entry,])


CN_MANN$Entry <- ifelse((CN_MANN$Entry_3 %in% Sequence_parameters$Entry)==TRUE & is.na(CN_MANN$Entry)==TRUE, CN_MANN$Entry_3,CN_MANN$Entry)

dim(CN_MANN[CN_MANN$Entry %in% Sequence_parameters$Entry,])

CN_MANN$Entry <- ifelse((CN_MANN$Entry_4 %in% Sequence_parameters$Entry)==TRUE & is.na(CN_MANN$Entry)==TRUE, CN_MANN$Entry_4,CN_MANN$Entry)

dim(CN_MANN[CN_MANN$Entry %in% Sequence_parameters$Entry,])


CN_MANN$Entry <- ifelse((CN_MANN$Entry_5 %in% Sequence_parameters$Entry)==TRUE & is.na(CN_MANN$Entry)==TRUE, CN_MANN$Entry_5,CN_MANN$Entry)

dim(CN_MANN[CN_MANN$Entry %in% Sequence_parameters$Entry,])


CN_MANN$Entry <- ifelse((CN_MANN$Entry_6 %in% Sequence_parameters$Entry)==TRUE & is.na(CN_MANN$Entry)==TRUE, CN_MANN$Entry_6,CN_MANN$Entry)

dim(CN_MANN[CN_MANN$Entry %in% Sequence_parameters$Entry,])



table(duplicated(CN_MANN$Entry))
CN_MANN[duplicated(CN_MANN$Entry)==TRUE,]

registerDoMC(4)
CN_MANN <- ddply(CN_MANN,"Entry", numcolwise(sum), .parallel = T, .progress = T)
dim(CN_MANN)


```


```{r CD4 Tn}

CD4_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("T4")) )
dim(CD4_MS)

CD4_CN_Tn <- NULL
CD4_CN_Tn$ID <- CD4_MS$Entry
CD4_CN_Tn$CN <- rowMeans(CD4_MS[,2:5])
CD4_CN_Tn <- data.frame(CD4_CN_Tn)

dim(CD4_CN_Tn)

CD4_CN_Tn$CN <- log10(CD4_CN_Tn$CN)
CD4_CN_Tn <- subset(CD4_CN_Tn, CD4_CN_Tn$CN>0)
dim(CD4_CN_Tn) # 7694 proteins expressed in  CD4 Tn !

write.table(CD4_CN_Tn,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD4_Tn_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(CD4_CN_Tn)
dim(CD4_CN_Tn[CD4_CN_Tn$ID %in% Sequence_parameters$Entry,])
```



```{r CD4 Tcm}

CD4_CN_Tcm <- NULL
CD4_CN_Tcm$ID <- CD4_MS$Entry
CD4_CN_Tcm$CN <- rowMeans(CD4_MS[,6:9])
CD4_CN_Tcm <- data.frame(CD4_CN_Tcm)

dim(CD4_CN_Tcm)

CD4_CN_Tcm$CN <- log10(CD4_CN_Tcm$CN)
CD4_CN_Tcm <- subset(CD4_CN_Tcm, CD4_CN_Tcm$CN>0)
dim(CD4_CN_Tcm) # 7751 proteins expressed in  CD4 Tcm !

write.table(CD4_CN_Tcm,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD4_Tcm_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```


```{r CD4 Tem}

CD4_CN_Tem <- NULL
CD4_CN_Tem$ID <- CD4_MS$Entry
CD4_CN_Tem$CN <- rowMeans(CD4_MS[,10:13])
CD4_CN_Tem <- data.frame(CD4_CN_Tem)

dim(CD4_CN_Tem)

CD4_CN_Tem$CN <- log10(CD4_CN_Tem$CN)
CD4_CN_Tem <- subset(CD4_CN_Tem, CD4_CN_Tem$CN>0)
dim(CD4_CN_Tem) # 7859 proteins expressed in  CD4 Tem !

write.table(CD4_CN_Tem,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD4_Tem_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```



```{r CD4 Teff}

CD4_CN_Teff <- NULL
CD4_CN_Teff$ID <- CD4_MS$Entry
CD4_CN_Teff$CN <- rowMeans(CD4_MS[,14:17])
CD4_CN_Teff <- data.frame(CD4_CN_Teff)

dim(CD4_CN_Teff)

CD4_CN_Teff$CN <- log10(CD4_CN_Teff$CN)
CD4_CN_Teff <- subset(CD4_CN_Teff, CD4_CN_Teff$CN>0)
dim(CD4_CN_Teff) # 7540 proteins expressed in  CD4 Teff !

write.table(CD4_CN_Teff,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD4_Teff_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```




```{r CD8 Tn}

CD8_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("T8")) )
dim(CD8_MS)

CD8_CN_Tn <- NULL
CD8_CN_Tn$ID <- CD8_MS$Entry
CD8_CN_Tn$CN <- rowMeans(CD8_MS[,2:5])
CD8_CN_Tn <- data.frame(CD8_CN_Tn)

dim(CD8_CN_Tn)

CD8_CN_Tn$CN <- log10(CD8_CN_Tn$CN)
CD8_CN_Tn <- subset(CD8_CN_Tn, CD8_CN_Tn$CN>0)
dim(CD8_CN_Tn) # 7986 proteins expressed in  CD8 Tn !

write.table(CD8_CN_Tn,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD8_Tn_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```




```{r CD8 Tcm}

CD8_CN_Tcm <- NULL
CD8_CN_Tcm$ID <- CD8_MS$Entry
CD8_CN_Tcm$CN <- rowMeans(CD8_MS[,6:9])
CD8_CN_Tcm <- data.frame(CD8_CN_Tcm)

dim(CD8_CN_Tcm)

CD8_CN_Tcm$CN <- log10(CD8_CN_Tcm$CN)
CD8_CN_Tcm <- subset(CD8_CN_Tcm, CD8_CN_Tcm$CN>0)
dim(CD8_CN_Tcm) # 8096 proteins expressed in  CD8 Tcm !

write.table(CD8_CN_Tcm,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD8_Tcm_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```



```{r CD8 Tem}

CD8_CN_Tem <- NULL
CD8_CN_Tem$ID <- CD8_MS$Entry
CD8_CN_Tem$CN <- rowMeans(CD8_MS[,10:13])
CD8_CN_Tem <- data.frame(CD8_CN_Tem)

dim(CD8_CN_Tem)

CD8_CN_Tem$CN <- log10(CD8_CN_Tem$CN)
CD8_CN_Tem <- subset(CD8_CN_Tem, CD8_CN_Tem$CN>0)
dim(CD8_CN_Tem) # 8106 proteins expressed in  CD8 Tem !

write.table(CD8_CN_Tem,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD8_Tem_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```




```{r CD8 Teff}

CD8_CN_Teff <- NULL
CD8_CN_Teff$ID <- CD8_MS$Entry
CD8_CN_Teff$CN <- rowMeans(CD8_MS[,14:17])
CD8_CN_Teff <- data.frame(CD8_CN_Teff)

dim(CD8_CN_Teff)

CD8_CN_Teff$CN <- log10(CD8_CN_Teff$CN)
CD8_CN_Teff <- subset(CD8_CN_Teff, CD8_CN_Teff$CN>0)
dim(CD8_CN_Teff) # 8030 proteins expressed in  CD8 Teff !

write.table(CD8_CN_Teff,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD8_Teff_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```






### Rest of blood cells ###


```{r B naive}

B_naive_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("B.naive")) )
dim(B_naive_MS)

B_naive_CN <- NULL
B_naive_CN$ID <- B_naive_MS$Entry
B_naive_CN$CN <- rowMeans(B_naive_MS[,2:5])
B_naive_CN <- data.frame(B_naive_CN)

dim(B_naive_CN)

B_naive_CN$CN <- log10(B_naive_CN$CN)
B_naive_CN <- subset(B_naive_CN, B_naive_CN$CN>0)
dim(B_naive_CN) # 7606 proteins expressed in  B_naive Tn !

write.table(B_naive_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/B_naive_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(B_naive_CN)
dim(B_naive_CN[B_naive_CN$ID %in% Sequence_parameters$Entry,])
```



```{r B mem}

B_mem_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("B.memory")) )
dim(B_mem_MS)

B_mem_CN <- NULL
B_mem_CN$ID <- B_mem_MS$Entry
B_mem_CN$CN <- rowMeans(B_mem_MS[,2:5])
B_mem_CN <- data.frame(B_mem_CN)

dim(B_mem_CN)

B_mem_CN$CN <- log10(B_mem_CN$CN)
B_mem_CN <- subset(B_mem_CN, B_mem_CN$CN>0)
dim(B_mem_CN) # 7839 proteins expressed in  B_mem Tn !

write.table(B_mem_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/B_mem_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(B_mem_CN)
dim(B_mem_CN[B_mem_CN$ID %in% Sequence_parameters$Entry,])
```




```{r B plasma}

B_plasma_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("B.plasma")) )
dim(B_plasma_MS)

B_plasma_CN <- NULL
B_plasma_CN$ID <- B_plasma_MS$Entry
B_plasma_CN$CN <- rowMeans(B_plasma_MS[,2:5])
B_plasma_CN <- data.frame(B_plasma_CN)

dim(B_plasma_CN)

B_plasma_CN$CN <- log10(B_plasma_CN$CN)
B_plasma_CN <- subset(B_plasma_CN, B_plasma_CN$CN>0)
dim(B_plasma_CN) # 6573 proteins expressed in  B_plasma Tn !

write.table(B_plasma_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/B_plasma_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(B_plasma_CN)
dim(B_plasma_CN[B_plasma_CN$ID %in% Sequence_parameters$Entry,])
```





```{r nTregs}

nTregs_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("nTregs")) )
dim(nTregs_MS)

nTregs_CN <- NULL
nTregs_CN$ID <- nTregs_MS$Entry
nTregs_CN$CN <- rowMeans(nTregs_MS[,2:5])
nTregs_CN <- data.frame(nTregs_CN)

dim(nTregs_CN)

nTregs_CN$CN <- log10(nTregs_CN$CN)
nTregs_CN <- subset(nTregs_CN, nTregs_CN$CN>0)
dim(nTregs_CN) # 7872 proteins expressed in  nTregs Tn !

write.table(nTregs_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/nTregs_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(nTregs_CN)
dim(nTregs_CN[nTregs_CN$ID %in% Sequence_parameters$Entry,])
```





```{r mTregs}

mTregs_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("mTregs")) )
dim(mTregs_MS)

mTregs_CN <- NULL
mTregs_CN$ID <- mTregs_MS$Entry
mTregs_CN$CN <- rowMeans(mTregs_MS[,2:5])
mTregs_CN <- data.frame(mTregs_CN)

dim(mTregs_CN)

mTregs_CN$CN <- log10(mTregs_CN$CN)
mTregs_CN <- subset(mTregs_CN, mTregs_CN$CN>0)
dim(mTregs_CN) # 8033 proteins expressed in  mTregs Tn !

write.table(mTregs_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/mTregs_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(mTregs_CN)
dim(mTregs_CN[mTregs_CN$ID %in% Sequence_parameters$Entry,])
```



```{r mDC}

mDC_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("mDC")) )
dim(mDC_MS)

mDC_CN <- NULL
mDC_CN$ID <- mDC_MS$Entry
mDC_CN$CN <- rowMeans(mDC_MS[,2:5])
mDC_CN <- data.frame(mDC_CN)

dim(mDC_CN)

mDC_CN$CN <- log10(mDC_CN$CN)
mDC_CN <- subset(mDC_CN, mDC_CN$CN>0)
dim(mDC_CN) # 8188 proteins expressed in  mDC Tn !

write.table(mDC_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/mDC_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(mDC_CN)
dim(mDC_CN[mDC_CN$ID %in% Sequence_parameters$Entry,])
```



```{r pDC}

pDC_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("pDC")) )
dim(pDC_MS)

pDC_CN <- NULL
pDC_CN$ID <- pDC_MS$Entry
pDC_CN$CN <- rowMeans(pDC_MS[,2:5])
pDC_CN <- data.frame(pDC_CN)

dim(pDC_CN)

pDC_CN$CN <- log10(pDC_CN$CN)
pDC_CN <- subset(pDC_CN, pDC_CN$CN>0)
dim(pDC_CN) # 8245 proteins expressed in  pDC Tn !

write.table(pDC_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/pDC_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(pDC_CN)
dim(pDC_CN[pDC_CN$ID %in% Sequence_parameters$Entry,])
```





```{r Basophils}

Basophils_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("Baso")) )
dim(Basophils_MS)

Basophils_CN <- NULL
Basophils_CN$ID <- Basophils_MS$Entry
Basophils_CN$CN <- rowMeans(Basophils_MS[,2:5])
Basophils_CN <- data.frame(Basophils_CN)

dim(Basophils_CN)

Basophils_CN$CN <- log10(Basophils_CN$CN)
Basophils_CN <- subset(Basophils_CN, Basophils_CN$CN>0)
dim(Basophils_CN) # 7911 proteins expressed in  Basophils Tn !

write.table(Basophils_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/Basophils_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(Basophils_CN)
dim(Basophils_CN[Basophils_CN$ID %in% Sequence_parameters$Entry,])
```



```{r Eosinophils}

Eosinophils_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("Eosino")) )
dim(Eosinophils_MS)

Eosinophils_CN <- NULL
Eosinophils_CN$ID <- Eosinophils_MS$Entry
Eosinophils_CN$CN <- rowMeans(Eosinophils_MS[,2:5])
Eosinophils_CN <- data.frame(Eosinophils_CN)

dim(Eosinophils_CN)

Eosinophils_CN$CN <- log10(Eosinophils_CN$CN)
Eosinophils_CN <- subset(Eosinophils_CN, Eosinophils_CN$CN>0)
dim(Eosinophils_CN) # 7434 proteins expressed in  Eosinophils Tn !

write.table(Eosinophils_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/Eosinophils_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(Eosinophils_CN)
dim(Eosinophils_CN[Eosinophils_CN$ID %in% Sequence_parameters$Entry,])  
```



```{r Neutrophils}

Neutrophils_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("Neutrophil")) )
dim(Neutrophils_MS)

Neutrophils_CN <- NULL
Neutrophils_CN$ID <- Neutrophils_MS$Entry
Neutrophils_CN$CN <- rowMeans(Neutrophils_MS[,2:5])
Neutrophils_CN <- data.frame(Neutrophils_CN)

dim(Neutrophils_CN)

Neutrophils_CN$CN <- log10(Neutrophils_CN$CN)
Neutrophils_CN <- subset(Neutrophils_CN, Neutrophils_CN$CN>0)
dim(Neutrophils_CN) # 6951 proteins expressed in  Neutrophils Tn !

write.table(Neutrophils_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/Neutrophils_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(Neutrophils_CN)
dim(Neutrophils_CN[Neutrophils_CN$ID %in% Sequence_parameters$Entry,])
```



```{r Mono_classical}

Mono_classical_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("MO.classical")) )
dim(Mono_classical_MS)

Mono_classical_CN <- NULL
Mono_classical_CN$ID <- Mono_classical_MS$Entry
Mono_classical_CN$CN <- rowMeans(Mono_classical_MS[,2:5])
Mono_classical_CN <- data.frame(Mono_classical_CN)

dim(Mono_classical_CN)

Mono_classical_CN$CN <- log10(Mono_classical_CN$CN)
Mono_classical_CN <- subset(Mono_classical_CN, Mono_classical_CN$CN>0)
dim(Mono_classical_CN) # 7862 proteins expressed in  Mono_classical Tn !

write.table(Mono_classical_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/Mono_classical_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(Mono_classical_CN)
dim(Mono_classical_CN[Mono_classical_CN$ID %in% Sequence_parameters$Entry,])
```




```{r Mono_inter}

Mono_intermediate_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("inter")) )
dim(Mono_intermediate_MS)

Mono_intermediate_CN <- NULL
Mono_intermediate_CN$ID <- Mono_intermediate_MS$Entry
Mono_intermediate_CN$CN <- rowMeans(Mono_intermediate_MS[,2:5])
Mono_intermediate_CN <- data.frame(Mono_intermediate_CN)

dim(Mono_intermediate_CN)

Mono_intermediate_CN$CN <- log10(Mono_intermediate_CN$CN)
Mono_intermediate_CN <- subset(Mono_intermediate_CN, Mono_intermediate_CN$CN>0)
dim(Mono_intermediate_CN) # 8118 proteins expressed in  Mono_intermediate Tn !

write.table(Mono_intermediate_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/Mono_intermediate_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(Mono_intermediate_CN)
dim(Mono_intermediate_CN[Mono_intermediate_CN$ID %in% Sequence_parameters$Entry,])
```




```{r Mono_non_class}

Mono_non_classical_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("nonclassical")) )
dim(Mono_non_classical_MS)

Mono_non_classical_CN <- NULL
Mono_non_classical_CN$ID <- Mono_non_classical_MS$Entry
Mono_non_classical_CN$CN <- rowMeans(Mono_non_classical_MS[,2:5])
Mono_non_classical_CN <- data.frame(Mono_non_classical_CN)

dim(Mono_non_classical_CN)

Mono_non_classical_CN$CN <- log10(Mono_non_classical_CN$CN)
Mono_non_classical_CN <- subset(Mono_non_classical_CN, Mono_non_classical_CN$CN>0)
dim(Mono_non_classical_CN) # 8184 proteins expressed in  Mono_non_classical Tn !

write.table(Mono_non_classical_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/Mono_non_classical_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(Mono_non_classical_CN)
dim(Mono_non_classical_CN[Mono_non_classical_CN$ID %in% Sequence_parameters$Entry,])
```





```{r NK_bright}

NK_bright_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("NK.bright")) )
dim(NK_bright_MS)

NK_bright_CN <- NULL
NK_bright_CN$ID <- NK_bright_MS$Entry
NK_bright_CN$CN <- rowMeans(NK_bright_MS[,2:5])
NK_bright_CN <- data.frame(NK_bright_CN)

dim(NK_bright_CN)

NK_bright_CN$CN <- log10(NK_bright_CN$CN)
NK_bright_CN <- subset(NK_bright_CN, NK_bright_CN$CN>0)
dim(NK_bright_CN) # 8153 proteins expressed in  NK_bright Tn !

write.table(NK_bright_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/NK_bright_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(NK_bright_CN)
dim(NK_bright_CN[NK_bright_CN$ID %in% Sequence_parameters$Entry,])
```



```{r NK_dim}

NK_dim_MS <- data.frame("Entry"=CN_MANN$Entry, CN_MANN %>% dplyr::select(contains("NK.dim")) )
dim(NK_dim_MS)

NK_dim_CN <- NULL
NK_dim_CN$ID <- NK_dim_MS$Entry
NK_dim_CN$CN <- rowMeans(NK_dim_MS[,2:5])
NK_dim_CN <- data.frame(NK_dim_CN)

dim(NK_dim_CN)

NK_dim_CN$CN <- log10(NK_dim_CN$CN)
NK_dim_CN <- subset(NK_dim_CN, NK_dim_CN$CN>0)
dim(NK_dim_CN) # 8089 proteins expressed in  NK_dim Tn !

write.table(NK_dim_CN,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/NK_dim_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

dim(NK_dim_CN)
dim(NK_dim_CN[NK_dim_CN$ID %in% Sequence_parameters$Entry,])
```












# CD4 Activation (Geiger Lab)

```{r CD4 immunomics.ch prep}
CN_Geiger <- read.delim("/home/ben/Analysis/RF_human/T_cell_subsets/Protein/Immunomics_CN.csv", sep = ",")
CN_Geiger$protein_name <- NULL
CN_Geiger$kDa <- NULL

table(duplicated(CN_Geiger$gene_name))

dim(CN_Geiger) # 7722   10

#Sequence_parameters_per_gene <- read.delim("/home/ben/Analysis/RF_human/Library_V2_Aug2021/Protein_per_gene_library_v2_RBP_GC_length_codon_AA_m6A_m5C_AtoI_m1A_m7G_CD8miRDB_PTM.csv", sep="\t", dec=".")

Uniprot_ref <- read.delim("/home/ben/Analysis/RF_human/sequences/uniprot-filtered-organism Homo+sapiens+(Human)+[9606] +AND+review--.tab")

Uniprot_ref$ID1 <- mapply(strsplit(as.character(Uniprot_ref$Gene.names)," "),FUN=function(x){(as.character(x)[1])})
Uniprot_ref$ID2 <- mapply(strsplit(as.character(Uniprot_ref$Gene.names)," "),FUN=function(x){(as.character(x)[2])})
Uniprot_ref$ID3 <- mapply(strsplit(as.character(Uniprot_ref$Gene.names)," "),FUN=function(x){(as.character(x)[3])})
Uniprot_ref$ID4 <- mapply(strsplit(as.character(Uniprot_ref$Gene.names)," "),FUN=function(x){(as.character(x)[4])})
Uniprot_ref$ID5 <- mapply(strsplit(as.character(Uniprot_ref$Gene.names)," "),FUN=function(x){(as.character(x)[5])})


dim(CN_Geiger[CN_Geiger$gene_name %in% Uniprot_ref$ID1,])
dim(CN_Geiger[CN_Geiger$gene_name %in% Uniprot_ref$ID2,])
dim(CN_Geiger[CN_Geiger$gene_name %in% Uniprot_ref$ID3,])
dim(CN_Geiger[CN_Geiger$gene_name %in% Uniprot_ref$ID4,])
dim(CN_Geiger[CN_Geiger$gene_name %in% Uniprot_ref$ID5,])



Uniprot_ref$ID[Uniprot_ref$ID1 %in% CN_Geiger$gene_name] <- Uniprot_ref$ID1[Uniprot_ref$ID1 %in% CN_Geiger$gene_name]
dim(Uniprot_ref[Uniprot_ref$ID %in% CN_Geiger$gene_name,])

Uniprot_ref[(Uniprot_ref$ID2 %in% CN_Geiger$gene_name)==TRUE & is.na(Uniprot_ref$ID)==TRUE,]

#Uniprot_ref$ID <- NULL
Uniprot_ref$ID <- ifelse(((Uniprot_ref$ID2 %in% CN_Geiger$gene_name)==TRUE & is.na(Uniprot_ref$ID)==TRUE), Uniprot_ref$ID2,Uniprot_ref$ID)
dim(Uniprot_ref[Uniprot_ref$ID %in% CN_Geiger$gene_name,])


Uniprot_ref$ID <- ifelse((Uniprot_ref$ID3 %in% CN_Geiger$gene_name)==TRUE & is.na(Uniprot_ref$ID)==TRUE, Uniprot_ref$ID3,Uniprot_ref$ID)
dim(Uniprot_ref[Uniprot_ref$ID %in% CN_Geiger$gene_name,])


Uniprot_ref$ID <- ifelse((Uniprot_ref$ID4 %in% CN_Geiger$gene_name)==TRUE & is.na(Uniprot_ref$ID)==TRUE, Uniprot_ref$ID4,Uniprot_ref$ID)
dim(Uniprot_ref[Uniprot_ref$ID %in% CN_Geiger$gene_name,])

Uniprot_ref$ID <- ifelse((Uniprot_ref$ID5 %in% CN_Geiger$gene_name)==TRUE & is.na(Uniprot_ref$ID)==TRUE, Uniprot_ref$ID5,Uniprot_ref$ID)
dim(Uniprot_ref[Uniprot_ref$ID %in% CN_Geiger$gene_name,])

Uniprot_ref <- Uniprot_ref[!is.na(Uniprot_ref$ID),]

dim(Uniprot_ref[duplicated(Uniprot_ref$ID),])

dim(CN_Geiger[duplicated(CN_Geiger$gene_name),])

Uniprot_ref <- data.frame("Entry"=Uniprot_ref$Entry,"ID"=Uniprot_ref$ID)

Uniprot_ref <- merge(Uniprot_ref,Sequence_parameters,by="Entry")

dim(Uniprot_ref)
# registerDoMC(4)
# Uniprot_ref <- ddply(Uniprot_ref,"ID", numcolwise(mean), .parallel = T, .progress = T)
# dim(Uniprot_ref)

Uniprot_ref_dups <- Uniprot_ref[duplicated(Uniprot_ref$ID,fromLast = T) |duplicated(Uniprot_ref$ID,fromLast = F),]
dim(Uniprot_ref_dups)
Uniprot_ref <- Uniprot_ref[!(duplicated(Uniprot_ref$ID,fromLast = T) |duplicated(Uniprot_ref$ID,fromLast = F)),]


registerDoMC(4)
Uniprot_ref_dups <- ddply(Uniprot_ref_dups,"ID", numcolwise(mean), .parallel = T, .progress = T)
dim(Uniprot_ref_dups)

Uniprot_ref$Entry <- NULL
Uniprot_ref <- rbind(Uniprot_ref,Uniprot_ref_dups)

dim(Uniprot_ref) # 7509 !

Uniprot_ref

write.table(Uniprot_ref,"/home/ben/Analysis/RF_human/sequences/Sequence_parameters_for_Geiger_data_prot_libv2_09092021.csv", sep=";", dec=",", quote = F,row.names = F)

```




```{r merging CN_Geiger and seq param}

CN_Geiger <- merge(CN_Geiger,Uniprot_ref,by.x="gene_name",by.y="ID")
dim(CN_Geiger) # 7509 7112

```



```{r CD4 Tn 0h}

CD4_Tn_0h <- data.frame("ID"=CN_Geiger$gene_name,"CN"=CN_Geiger$t.0h)
colnames(CD4_Tn_0h)[1:2] <- c("ID","CN")
CD4_Tn_0h$CN <- log10(CD4_Tn_0h$CN)
CD4_Tn_0h <- subset(CD4_Tn_0h,CD4_Tn_0h$CN>0)
dim(CD4_Tn_0h) # 6924

write.table(CD4_Tn_0h,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD4_Tn_0h_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```



```{r CD4 Tn 6h}

CD4_Tn_6h <- CN_Geiger[,c(1,3)]
colnames(CD4_Tn_6h)[1:2] <- c("ID","CN")
CD4_Tn_6h$CN <- log10(CD4_Tn_6h$CN)
CD4_Tn_6h <- subset(CD4_Tn_6h,CD4_Tn_6h$CN>0)
dim(CD4_Tn_6h) # 6540

write.table(CD4_Tn_6h,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD4_Tn_6h_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```



```{r CD4 Tn 12h}

CD4_Tn_12h <- CN_Geiger[,c(1,4)]
colnames(CD4_Tn_12h)[1:2] <- c("ID","CN")
CD4_Tn_12h$CN <- log10(CD4_Tn_12h$CN)
CD4_Tn_12h <- subset(CD4_Tn_12h,CD4_Tn_12h$CN>0)
dim(CD4_Tn_12h) # 6711

write.table(CD4_Tn_12h,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD4_Tn_12h_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```



```{r CD4 Tn 24h}

CD4_Tn_24h <- CN_Geiger[,c(1,5)]
colnames(CD4_Tn_24h)[1:2] <- c("ID","CN")
CD4_Tn_24h$CN <- log10(CD4_Tn_24h$CN)
CD4_Tn_24h <- subset(CD4_Tn_24h,CD4_Tn_24h$CN>0)
dim(CD4_Tn_24h) # 6257

write.table(CD4_Tn_24h,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD4_Tn_24h_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```




```{r CD4 Tn 48h}

CD4_Tn_48h <- CN_Geiger[,c(1,6)]
colnames(CD4_Tn_48h)[1:2] <- c("ID","CN")
CD4_Tn_48h$CN <- log10(CD4_Tn_48h$CN)
CD4_Tn_48h <- subset(CD4_Tn_48h,CD4_Tn_48h$CN>0)
dim(CD4_Tn_48h) # 6913

write.table(CD4_Tn_48h,"/home/ben/Analysis/RF_human/T_cell_subsets/Protein/CD4_Tn_48h_CN_log10.csv",sep = ";",dec = ",",row.names = F,quote = F)

```
